id: P000471
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:39.103884
source_metadata:
  id: bdr:W1GS8
  title: ཕྱག་རྡོར་གསོ་རིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    cd912a55a5944011a7b3177f1c2c33e1:
      image_group_id: I1PD452
      title: Volume 1 of phyag rdor gso rig phyogs bsgrigs
      volume_number: 1
      total_pages: 500
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
