id: I3B9EF1A6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T22:59:10+00:00'
last_modified: '2022-06-15T18:49:18.430788+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS8
  title: ཕྱག་རྡོར་གསོ་རིག་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    52FD:
      image_group_id: I1PD452
      title: Volume 1 of phyag rdor gso rig phyogs bsgrigs
      total_pages: 500
      order: 1
      base_file: 52FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
